FROM node:12.16.1-alpine

WORKDIR /code

# Install and cache app dependencies
COPY frontend/package.json .
COPY frontend/yarn.lock .
RUN yarn install

# Expose port
EXPOSE 3000

# Run development server in runtime
CMD sleep infinity
