FROM node:12.16.1-alpine

WORKDIR /code

# Install and cache app dependencies
COPY frontend/package.json .
COPY frontend/yarn.lock .
RUN yarn install

ENV PORT=80
# Run development server in runtime
CMD yarn start