version: "3.7"

services:
  launcher:
    container_name: leap-launcher-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: launcherserver
    network_mode: host
    environment:
      - SUDO_USER=${SUDO_USER}
      - SUDO_PASS=${SUDO_PASS}
    volumes:
      - ./src:/code
      - /home/jose/.ssh/id_rsa/:/code/launcher/id_rsa
    # command: ['sleep', 'infinity']
  nginx:
    container_name: leap-launcher-nginx
    image: nginx:1.13.1
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend.html:/usr/src/leap-launcher/frontend/index.html