version: "3.7"

services:
  launcher:
    container_name: leap-launcher-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: launcherserver
    network_mode: host
    environment:
      - SUDO_USER=${SUDO_USER}
      - SUDO_PASS=${SUDO_PASS}
    volumes:
      - ./src:/code
      - /home/jose/.ssh/id_rsa/:/code/launcher/id_rsa
    # command: ['sleep', 'infinity']

  frontend:
    stdin_open: true
    container_name: leap-launcher-frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    network_mode: host
    image: launcherfrontend
    volumes:
      - ./frontend:/code
    depends_on:
      - launcher
    restart: always