version: "3.7"

services:
  launcher:
    build:
      context: .
      dockerfile: Dockerfile
    image: launcherserver
    network_mode: host
    environment:
      - SUDO_USER=${SUDO_USER}
      - SUDO_PASS=${SUDO_PASS}
    volumes:
      - ./src:/code
      - /home/jose/.ssh/id_rsa/:/code/launcher/id_rsa
    # command: ['sleep', 'infinity']
    
